name: GolangLambdasToS3

on:
  push:
    branches: [ main, development, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  Test:
    name: Test package against last 3 Go versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go: [1.18, 1.19, 1.20.0]
        os:   [ubuntu-20.04]
    steps:
    - name: Set up Checkout
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go }}

    - name: Run tests
      run: go test -v ./...

  PushToS3:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Set up Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - name: Create deploy folder
        run: mkdir ./deploy
      - name: Build Go function
        run: GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags lambda.norpc -o bootstrap main.go
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r ./deploy/lambda.zip bootstrap
      - name: Upload Go function
        uses: actions/upload-artifact@v2
        with:
          name: lambda.zip
          path: ./deploy

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            eu-west-2

      - name: Upload to S3
        run: aws s3 cp ./deploy/lambda.zip s3://${{secrets.AWS_BUCKET_NAME}}/lambda.zip
